<?php echo $this->pageTitle($this->translate('Past Zotero imports and exports'));
$this->htmlElement('body')->appendAttribute('class', 'browse');
$this->htmlElement('body')->appendAttribute('class', 'past-imports');
$this->headLink()->appendStylesheet($this->assetUrl('css/zoteroimport.css', 'ZoteroImport'));
?>

<?php if (!$imports): ?>
<p><?php echo $this->translate('There are no Zotero imports or exports.'); ?></p>
<?php else: ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>
<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
    <tr>
        <th><?php echo $this->translate('Zotero Library'); ?></th>
        <th><?php echo $this->translate('Items Added Before'); ?></th>
        <th><?php echo $this->translate('Job Status'); ?></th>
        <th><?php echo $this->translate('Item Count'); ?></th>
    </tr>
    </thead>
    <tbody>
<?php foreach ($imports as $import): ?>
    <?php
    $job = $import->job();
    $undoJob = $import->undoJob();
    $jobType = $job ? ($job->jobClass() === \ZoteroImport\Job\Export::class ? 'export' : 'import') : null;
    ?>
    <tr>
        <td>
            <?php echo $this->hyperlink($import->name(), $import->libraryUrl()); ?>
            <ul class="actions">
                <?php if (
                    $job
                    && $jobType === 'import'
                    && in_array($job->status(), ['completed', 'stopped', 'error'])
                    && (!$undoJob || in_array($undoJob->status(), ['stopped', 'error']))
                ): ?>
                <li><a href="#"
                    data-sidebar-content-url="<?php echo $this->escapeHtml($import->url('undo-confirm')); ?>"
                    class="o-icon-undo sidebar-content"
                    aria-label="<?php echo $this->translate('Undo import'); ?>"
                    title="<?php echo $this->translate('Undo import'); ?>"></a></li>
                <?php endif; ?>
            </ul>
        </td>
        <td>
            <?php if ($job): ?>
                <?php echo $this->i18n()->dateFormat($job->started(), 'medium', 'medium'); ?>
            <?php else: ?>
                <?php echo $this->translate('Unknown'); ?>
            <?php endif; ?>
        </td>
        <td>
            <?php if ($job): ?>
                <?php switch ($jobType):
                case 'import': ?>
                    <?php echo $this->hyperlink(sprintf($this->translate('Import %s'), $this->translate($job->statusLabel())), $job->url()); ?>
                    <?php if ($undoJob): ?>
                    <br>
                    <?php echo $this->hyperlink(sprintf($this->translate('Undo Import %s'), $this->translate($undoJob->statusLabel())), $undoJob->url()); ?>
                    <?php endif; ?>
                    <?php break;
                case 'export': ?>
                    <?php echo $this->hyperlink(sprintf($this->translate('Export %s'), $this->translate($job->statusLabel())), $job->url()); ?>
                    <?php break;
                endswitch; ?>
            <?php else: ?>
                <?php echo $this->translate('Unknown'); ?>
            <?php endif; ?>
        </td>
        <td><?php echo $this->hyperlink(
            $import->importItemCount(),
            $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['zotero_import_id' => $import->id()]])
        ); ?></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>
<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $this->translate('Close'); ?>"
        title="<?php echo $this->translate('Close'); ?>"></a>
    <div class="sidebar-content"></div>
</div>
<?php endif; ?>
