<?php echo $this->pageTitle($this->translate('Zotero Import')); ?>
<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\ZoteroImport')->menu(); ?>
</nav>
<?php if (!$imports): ?>
<p><?php echo $this->translate('There are no Zotero imports.'); ?></p>
<?php else: ?>
<table>
    <thead>
    <tr>
        <th><?php echo $this->translate('Library'); ?></th>
        <th><?php echo $this->translate('Version'); ?></th>
        <th><?php echo $this->translate('Job Status'); ?></th>
        <th><?php echo $this->translate('Job Started'); ?></th>
    </tr>
    </thead>
    <tbody>
<?php foreach ($imports as $import): ?>
    <?php $job = $import->job(); ?>
    <tr>
        <td><?php echo $this->hyperlink($import->name(), $import->libraryUrl()); ?></td>
        <td><?php echo $import->version(); ?></td>
        <td><?php echo $job->statusLabel(); ?></td>
        <td><?php echo $this->i18n()->dateFormat($job->started(), 'medium', 'medium'); ?></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
