<?php echo $this->pageTitle($this->translate('Zotero Import')); ?>
<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\ZoteroImport')->menu(); ?>
</nav>
<?php if (!$imports): ?>
<p><?php echo $this->translate('There are no Zotero imports.'); ?></p>
<?php else: ?>
<?php echo $this->pagination(); ?>
<table class="tablesaw tablesaw-stack">
    <thead>
    <tr>
        <th><?php echo $this->translate('Zotero Library'); ?></th>
        <th><?php echo $this->translate('Items Added Before'); ?></th>
        <th><?php echo $this->translate('Job Status'); ?></th>
    </tr>
    </thead>
    <tbody>
<?php foreach ($imports as $import): ?>
    <?php $job = $import->job(); ?>
    <tr>
        <td><?php echo $this->hyperlink($import->name(), $import->libraryUrl()); ?></td>
        <td><?php echo $this->i18n()->dateFormat($job->started(), 'medium', 'medium'); ?></td>
        <td><?php echo $this->hyperlink($job->statusLabel(), $job->url()); ?></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->pagination(); ?>
<?php endif; ?>
