<?php $form->prepare(); ?>
<?php echo $this->pageTitle($this->translate('Zotero Import')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->escapeHtml($this->translate('Submit')); ?></button>
</div>
<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\ZoteroImport')->menu(); ?>
</nav>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>
