<?php
return array(
    'author'         => array('dcterms' => 'creator'),
    'contributor'    => array('dcterms' => 'contributor'),
    'editor'         => array('bibo' => 'editor'),
    'translator'     => array('bibo' => 'translator'),
    'seriesEditor'   => array('bibo' => 'editor'),
    'interviewee'    => array('bibo' => 'interviewee'),
    'interviewer'    => array('bibo' => 'interviewer'),
    'director'       => array('bibo' => 'director'),
    'scriptwriter'   => array(),
    'producer'       => array('bibo' => 'producer'),
    'castMember'     => array(),
    'sponsor'        => array(),
    'counsel'        => array(),
    'inventor'       => array(),
    'attorneyAgent'  => array(),
    'recipient'      => array('bibo' => 'recipient'),
    'performer'      => array('bibo' => 'performer'),
    'composer'       => array(),
    'wordsBy'        => array(),
    'cartographer'   => array(),
    'programmer'     => array(),
    'reviewedAuthor' => array(),
    'artist'         => array(),
    'commenter'      => array(),
    'presenter'      => array(),
    'guest'          => array(),
    'podcaster'      => array(),
    'cosponsor'      => array(),
    'bookAuthor'     => array('dcterms' => 'creator'),
);
