<?php
return [
    'author'         => ['dcterms' => 'creator'],
    'contributor'    => ['dcterms' => 'contributor'],
    'editor'         => ['bibo' => 'editor'],
    'translator'     => ['bibo' => 'translator'],
    'seriesEditor'   => ['bibo' => 'editor'],
    'interviewee'    => ['bibo' => 'interviewee'],
    'interviewer'    => ['bibo' => 'interviewer'],
    'director'       => ['bibo' => 'director'],
    'scriptwriter'   => [],
    'producer'       => ['bibo' => 'producer'],
    'castMember'     => [],
    'sponsor'        => [],
    'counsel'        => [],
    'inventor'       => [],
    'attorneyAgent'  => [],
    'recipient'      => ['bibo' => 'recipient'],
    'performer'      => ['bibo' => 'performer'],
    'composer'       => [],
    'wordsBy'        => [],
    'cartographer'   => [],
    'programmer'     => [],
    'reviewedAuthor' => [],
    'artist'         => [],
    'commenter'      => [],
    'presenter'      => [],
    'guest'          => [],
    'podcaster'      => [],
    'cosponsor'      => [],
    'bookAuthor'     => ['dcterms' => 'creator'],
];
