<?php
return array(
    'artwork'             => array('bibo' => 'Image'),
    //'attachment'          => 'z:Attachment',
    'audioRecording'      => array('bibo' => 'AudioDocument'),
    'bill'                => array('bibo' => 'Bill'),
    'blogPost'            => array('bibo' => 'Article'),
    'book'                => array('bibo' => 'Book'),
    'bookSection'         => array('bibo' => 'BookSection'),
    'case'                => array('bibo' => 'LegalCaseDocument'),
    'computerProgram'     => array('bibo' => 'Document'),
    'conferencePaper'     => array('bibo' => 'Article'),
    'dictionaryEntry'     => array('bibo' => 'Article'),
    'document'            => array('bibo' => 'Document'),
    'email'               => array('bibo' => 'Email'),
    'encyclopediaArticle' => array('bibo' => 'Article'),
    'film'                => array('bibo' => 'Film'),
    'forumPost'           => array('bibo' => 'Article'),
    'hearing'             => array('bibo' => 'Hearing'),
    'instantMessage'      => array('bibo' => 'PersonalCommunication'),
    'interview'           => array('bibo' => 'Interview'),
    'journalArticle'      => array('bibo' => 'AcademicArticle'),
    'letter'              => array('bibo' => 'Letter'),
    'magazineArticle'     => array('bibo' => 'Article'),
    'manuscript'          => array('bibo' => 'Manuscript'),
    'map'                 => array('bibo' => 'Map'),
    'newspaperArticle'    => array('bibo' => 'Article'),
    'note'                => array('bibo' => 'Note'),
    'patent'              => array('bibo' => 'Patent'),
    'podcast'             => array('bibo' => 'AudioDocument'),
    'presentation'        => array('bibo' => 'Slideshow'),
    'radioBroadcast'      => array('bibo' => 'AudioDocument'),
    'report'              => array('bibo' => 'Report'),
    'statute'             => array('bibo' => 'Statute'),
    'tvBroadcast'         => array('bibo' => 'AudioVisualDocument'),
    'thesis'              => array('bibo' => 'Thesis'),
    'videoRecording'      => array('bibo' => 'AudioVisualDocument'),
    'webpage'             => array('bibo' => 'Webpage'),
);
