<?php
return array(
    'numPages'             => array('bibo' => 'numPages'),
    'numberOfVolumes'      => array('bibo' => 'numberOfVolumes'),
    'abstractNote'         => array('dcterms' => 'abstract'),
    'accessDate'           => array(),
    'applicationNumber'    => array('bibo' => 'number'),
    'archive'              => array('dcterms' => 'publisher'),
    'artworkSize'          => array('dcterms' => 'extent'),
    'assignee'             => array(),
    'billNumber'           => array('bibo' => 'number'),
    'blogTitle'            => array('dcterms' => 'publisher'),
    'bookTitle'            => array('dcterms' => 'isPartOf'),
    'callNumber'           => array('bibo' => 'lccn'),
    'caseName'             => array('dcterms' => 'title'),
    'code'                 => array('dcterms' => 'title'),
    'codeNumber'           => array('bibo' => 'number'),
    'codePages'            => array(),
    'codeVolume'           => array(),
    'committee'            => array('bibo' => 'organizer'),
    'company'              => array(),
    'conferenceName'       => array('bibo' => 'presentedAt'),
    'country'              => array('dcterms' => 'publisher'),
    'court'                => array('bibo' => 'court'),
    'DOI'                  => array('bibo' => 'doi'),
    'date'                 => array('dcterms' => 'date'),
    'dateDecided'          => array(),
    'dateEnacted'          => array(),
    'dictionaryTitle'      => array('dcterms' => 'isPartOf'),
    'distributor'          => array('bibo' => 'distributor'),
    'docketNumber'         => array('bibo' => 'number'),
    'documentNumber'       => array('bibo' => 'number'),
    'edition'              => array('bibo' => 'edition'),
    'encyclopediaTitle'    => array('dcterms' => 'isPartOf'),
    'episodeNumber'        => array('bibo' => 'number'),
    'extra'                => array(),
    'audioFileType'        => array('dcterms' => 'type'),
    'filingDate'           => array('dcterms' => 'dateSubmitted'),
    'firstPage'            => array('bibo' => 'pageStart'),
    'audioRecordingFormat' => array('dcterms' => 'format'),
    'videoRecordingFormat' => array('dcterms' => 'format'),
    'forumTitle'           => array('dcterms' => 'publisher'),
    'genre'                => array('dcterms' => 'type'),
    'history'              => array(),
    'ISBN'                 => array('bibo' => 'isbn'),
    'ISSN'                 => array('bibo' => 'issn'),
    'institution'          => array(),
    'issue'                => array('bibo' => 'issue'),
    'issueDate'            => array('dcterms' => 'issued'),
    'issuingAuthority'     => array('bibo' => 'issuer'),
    'journalAbbreviation'  => array('bibo' => 'shortTitle'),
    'label'                => array(),
    'language'             => array('dcterms' => 'language'),
    'programmingLanguage'  => array(),
    'legalStatus'          => array('bibo' => 'status'),
    'legislativeBody'      => array('bibo' => 'organizer'),
    'libraryCatalog'       => array(),
    'archiveLocation'      => array('dcterms' => 'source'),
    'interviewMedium'      => array('dcterms' => 'medium'),
    'artworkMedium'        => array('dcterms' => 'medium'),
    'meetingName'          => array('bibo' => 'presentedAt'),
    'nameOfAct'            => array(),
    'network'              => array(),
    'pages'                => array('bibo' => 'pages'),
    'patentNumber'         => array('bibo' => 'number'),
    'place'                => array('dcterms' => 'publisher'),
    'postType'             => array('dcterms' => 'type'),
    'priorityNumbers'      => array(),
    'proceedingsTitle'     => array('dcterms' => 'isPartOf'),
    'programTitle'         => array('dcterms' => 'isPartOf'),
    'publicLawNumber'      => array('bibo' => 'number'),
    'publicationTitle'     => array('dcterms' => 'title'),
    'publisher'            => array('dcterms' => 'publisher'),
    'references'           => array(),
    'reportNumber'         => array('bibo' => 'number'),
    'reportType'           => array('dcterms' => 'type'),
    'reporter'             => array('dcterms' => 'title'),
    'reporterVolume'       => array(),
    'rights'               => array('dcterms' => 'rights'),
    'runningTime'          => array('dcterms' => 'extent'),
    'scale'                => array('dcterms' => 'extent'),
    'section'              => array('bibo' => 'section'),
    'series'               => array('dcterms' => 'title'),
    'seriesNumber'         => array('bibo' => 'number'),
    'seriesText'           => array('dcterms' => 'description'),
    'seriesTitle'          => array('dcterms' => 'title'),
    'session'              => array('bibo' => 'presentedAt'),
    'shortTitle'           => array('bibo' => 'shortTitle'),
    'studio'               => array(),
    'subject'              => array('dcterms' => 'subject'),
    'system'               => array(),
    'title'                => array('dcterms' => 'title'),
    'thesisType'           => array('dcterms' => 'type'),
    'mapType'              => array('dcterms' => 'type'),
    'manuscriptType'       => array('dcterms' => 'type'),
    'letterType'           => array('dcterms' => 'type'),
    'presentationType'     => array('dcterms' => 'type'),
    'url'                  => array('bibo' => 'uri'),
    'university'           => array(),
    'versionNumber'        => array('bibo' => 'number'),
    'volume'               => array('bibo' => 'volume'),
    'websiteTitle'         => array('dcterms' => 'publisher'),
    'websiteType'          => array('dcterms' => 'type'),
);
